### PR TITLE
Ostrava: Feedback for homeworks

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by hroncok** [comment]
This have failed the build on CI.

    naucse.sanitize.DisallowedLink: bart-chalkboard.gif

**Comment by hroncok** [comment]
https://travis-ci.org/PyLadiesCZ/naucse.python.cz - I don't have sufficient rights to enable this repo on Travis. Can somebody please do, we we would get the error on this fork on the PR instead of on main naucse after it's merged?

The failure:  https://travis-ci.org/pyvec/naucse.python.cz/builds/505129510

**Comment by frenzymadness** [comment]
I monitor Travis manually after every merge so I did in this case as well and fixed the issue.

**Comment by frenzymadness** [comment]
https://travis-ci.org/pyvec/naucse.python.cz/builds/505141496

**Comment by frenzymadness** [comment]
Travis for this repository enabled.

**Pull request merged**
